ALTER TABLE public.bookings
ADD COLUMN IF NOT EXISTS deposit_amount DECIMAL(10, 2) NOT NULL DEFAULT 100,
ADD COLUMN IF NOT EXISTS deposit_paid BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS deposit_paid_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS whatsapp_notified BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS whatsapp_notified_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS contract_sent BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS contract_sent_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS contract_signed BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS contract_signed_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS remaining_paid BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS remaining_paid_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS payment_notes TEXT;
